name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.10.4'
      - name: Install dependencies
        run: julia --project=GraphNeuralNetworks/docs/ -e '
          using Pkg;
          Pkg.develop([PackageSpec(path=joinpath(pwd(), "GraphNeuralNetworks")), 
                       PackageSpec(path=joinpath(pwd(), "GNNGraphs")),
                       PackageSpec(path=joinpath(pwd(), "GNNlib"))]);
          Pkg.instantiate();'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=GraphNeuralNetworks/docs/ GraphNeuralNetworks/docs/make.jl
